### ISSUE TITLE
"attempted to add a method" in empty redefine transformation with public class which inherits package-private class

### ISSUE THREAD

**Issue by oleksiyp** [raphw/byte-buddy#561] opened 2018-11-10 19:08 UTC
Following exception is happening with default and public classes involved:

```
Exception in thread "main" java.lang.UnsupportedOperationException: class redefinition failed: attempted to add a method
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at abc.B.main(B.java:68)
```

It is caused because of the difference in synthetic methods.

Here is minimum reproducible code:
```
package abc;

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.agent.ByteBuddyAgent;
import net.bytebuddy.dynamic.ClassFileLocator;

import java.lang.instrument.ClassFileTransformer;
import java.lang.instrument.IllegalClassFormatException;
import java.lang.instrument.Instrumentation;
import java.lang.instrument.UnmodifiableClassException;
import java.security.ProtectionDomain;

class Transform implements ClassFileTransformer {
    @Override
    public byte[] transform(
            ClassLoader loader,
            String className,
            Class<?> classBeingRedefined,
            ProtectionDomain protectionDomain,
            byte[] classfileBuffer
    ) throws IllegalClassFormatException {
        if (!className.equals("abc/B")) {
            return classfileBuffer;
        }
        try {
            return new ByteBuddy()
                    .redefine(classBeingRedefined,
                            ClassFileLocator.Simple.of(
                                    classBeingRedefined.getName(),
                                    classfileBuffer
                            )
                    )
                    .make()
                    .getBytes();
        } catch (Exception ex) {
            ex.printStackTrace();
            return classfileBuffer;
        }
    }
}

abstract class A<T extends A<T>> {
    public T operation() {
        return (T) this;
    }
}

public class B extends A<B> {
    public static void main(String[] args) throws UnmodifiableClassException, InterruptedException {
        Instrumentation instrumentation = ByteBuddyAgent.install();
        Class<B> bClass = B.class;
        instrumentation.addTransformer(new Transform(), true);
        instrumentation.retransformClasses(bClass);
    }
}
```

Related to https://github.com/mockk/mockk/issues/119

**Comment by raphw** [comment] 2018-11-12 21:00
I just ran this example and cannot reproduce any error. Are you running any form of code coverage tool from your IDE maybe?

**Comment by oleksiyp** [comment] 2018-11-12 21:21
Running from IDE without code coverage. 

I don't think it should be affected by IDE as it seems a problem with the amount of generated synthetic methods by a Java Compiler and by ByteBuddy.

Now I tried without IDE and it still reproducable:
```
0 ✓ oleksiyp@zen76:~/workspace/playground-kt13/out/production/classes$ /usr/lib/jvm/java-8-oracle/bin/java -cp /home/oleksiyp/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy/1.8.22/4d65fdf7d9755ef7c75f2213f356119d0e68c2cd/byte-buddy-1.8.22.jar:/home/oleksiyp/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.8.22/347d063fe292e406f6a71ff64dfd9e8d794f0aba/byte-buddy-agent-1.8.22.jar:. abc.B
Exception in thread "main" java.lang.UnsupportedOperationException: class redefinition failed: attempted to add a method
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at abc.B.main(B.java:68)
1 ✗ oleksiyp@zen76:~/workspace/playground-kt13/out/production/classes$ /usr/lib/jvm/java-8-oracle/bin/java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by oleksiyp** [comment] 2018-11-27 07:29
Hi @raphw, any updates regarding this issue?

**Comment by raphw** [comment] 2018-11-27 07:46
I have not had proper time to investigate this in detail but as said, I have trouble reproducing this. What IDE and exact JVM version are you using?

**Comment by oleksiyp** [comment] 2018-11-27 07:54
No worries, 1.8.0_191, no IDE is needed

**Comment by oleksiyp** [comment] 2018-12-25 08:00
Hi @raphw, any updates regarding this issue?

**Comment by raphw** [comment] 2019-01-05 22:49
I got it running and I am planning to fix it, sorry for the delay.

**Comment by raphw** [comment] 2019-01-05 23:18
By the way, it took me a while to understand this to begin with and it lead me to a bug in javac that has always existed. javac does not create a visibility bridge what makes it impossible to call `operation` reflectively from outside the package. If you remove the generic type, javac creates the access bridge as you would expect it. Byte Buddy is in a way fixing the missing bridge by accident. I have to add means to explicitly skip the bridge creation what is a bit tricky as it might come from a change in the type hierarchy that was explicitly requested as for example by adding an interface.

I have also reported this issue to the OpenJDK so this problem will hopefully disappear away either way but I think that I can add a solution in Byte Buddy.

**Comment by oleksiyp** [comment] 2019-01-06 09:49
sure, I suspected that this is some kind of optimization in the compiler or alike

**Comment by raphw** [comment] 2019-01-16 21:15
Ok, this turns out to be a bug in Java 8 that was not backported after being fixed in Java 11. Technically, the visibility bridge needs to be there and Byte Buddy adds it since it cannot know that the original class file was based on the same subclass.

It is of course unfortunate that this happens. For your use case, could you use the `decorate` option to avoid this? It would improve performance over `redefine` but allow class file changing operations. It is mainly meant for folks that just want to use advice.

**Comment by oleksiyp** [comment] 2019-01-16 21:18
Thanks. I see. Let me try `decorate`

**Comment by raphw** [comment] 2019-01-24 20:04
You can now set `VisibilityBridgeStrategy.Default.NEVER` on the `ByteBuddy` instance.

**Closed by raphw** 2019-01-24 20:04 UTC
Labels: question
