### ISSUE TITLE
Annotation with double array member cannot find proper targets

### ISSUE THREAD

**Issue by lujiajing1126** [raphw/byte-buddy#971] opened 2020-11-13 10:17 UTC
It seems to be a regression #725

 If I add `double[]` member in an annotation and use this method to annotate a method which should be intercepted, then it is not able to find proper targets in `MethodDelegationBinder`.

But if I remove this field, everything is fine.

**Comment by lujiajing1126** [comment] 2020-11-13 14:16
I have create a minimal example to illustrate the problem, see https://github.com/lujiajing1126/bytebuddy-issue971

If you build the `:app` module with `double[] percentiles default {}` in the `Timed` annotation, then the interceptor does not work with the original output `called`. 

Otherwise, it will output `intercept`.

**Comment by raphw** [comment] 2020-11-15 22:16
I cannot really reproduce this, the example fails to intercept in any case due to the `@SuperMethodCall` instruction.

I recommend you to use `Advice` when retransforming loaded classes, which is much more friendly to retransformation thanks to the approach of weaving code.

**Comment by CrocoRyan** [comment] 2020-11-16 15:33
Hey, I also came across this problem in practice. I built @lujiajing1126's project and it came out the same as he described. 
To better demonstrate this issue, I helped him build his app & agent modules to jar files and make a release at `https://github.com/lujiajing1126/bytebuddy-issue971/releases/tag/1.0-SNAPSHOT`
I'd be much appreciated if you can check it out again

**Comment by raphw** [comment] 2020-12-06 21:51
Maybe I am missing something, I get the following output:

> rafael@raftop:~/Downloads$ java -version
> openjdk version "1.8.0_275"
> OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
> OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
> rafael@raftop:~/Downloads$ java -javaagent:shadow-1.0-SNAPSHOT-all.jar -jar app-1.0-SNAPSHOT.jar
> intercept

**Comment by CrocoRyan** [comment] 2020-12-09 09:53
I add a github action to the project in order to compare the two cases thus make this issue more understandable. 
See at https://github.com/lujiajing1126/bytebuddy-issue971/runs/1522946854
Both of the two cases are supposed to come up with the result `intercept`, which indicates that the interceptor functions properly
However, as you can see in the result of the first run, `called` was printed instead of `intercept`, showing that the interceptor didn't function . And when I remove the Double member in the Timed annotation in the second run, interceptor get back to work, and come up with the expected result

**Comment by raphw** [comment] 2020-12-09 23:02
Alright, I finally figured it out and it is related to this: https://gitlab.ow2.org/asm/asm/-/issues/317923

Thanks for the patience and reproduction, this is now fixed on master.

**Comment by lujiajing1126** [comment] 2020-12-10 01:52
> Alright, I finally figured it out and it is related to this: https://gitlab.ow2.org/asm/asm/-/issues/317923
> 
> Thanks for the patience and reproduction, this is now fixed on master.

I have switched `byte-buddy` to the master-SNAPSHOT version. The CI seems to be happy.

Many thanks! A pleasure that we can help. Just wait for the next release.

**Closed** 2021-04-16 12:12 UTC
Labels: bug
