### ISSUE TITLE
Gradle plugin fails with `mvn package`

### ISSUE THREAD

**Issue by clankill3r** [raphw/byte-buddy#595] opened 2019-01-25 19:37 UTC
From https://bytebuddy.net/#/develop I try to execute the following commands:

```
    git clone https://github.com/raphw/byte-buddy.git
    cd byte-buddy
    mvn package
```

The first 2 are a no brainer, but on the `mvn package` I get:

<img width="1440" alt="screen shot 2019-01-25 at 20 31 48" src="https://user-images.githubusercontent.com/738650/51768426-91a84d00-20e0-11e9-91bb-c9407e1b51f1.png">

Here as text:

```
BUILD FAILED in 21s
1 actionable task: 1 executed
[INFO] Run build
[INFO] Build
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Byte Buddy (parent) ................................ SUCCESS [  4.513 s]
[INFO] Byte Buddy Java agent .............................. SUCCESS [ 12.489 s]
[INFO] Byte Buddy (with dependencies) ..................... SUCCESS [ 48.894 s]
[INFO] Byte Buddy (without dependencies) .................. SUCCESS [  3.920 s]
[INFO] Byte Buddy benchmarks .............................. SUCCESS [  4.546 s]
[INFO] Byte Buddy for Android ............................. SUCCESS [  4.314 s]
[INFO] Byte Buddy (Maven plugin) .......................... SUCCESS [  6.700 s]
[INFO] Byte Buddy (Gradle plugin) ......................... FAILURE [ 25.579 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:51 min
[INFO] Finished at: 2019-01-25T19:25:08+01:00
[INFO] Final Memory: 53M/184M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal codes.rafael.gradlemavenplugin:gradle-maven-plugin:1.0.10:invoke (gradle-build) on project byte-buddy-gradle-plugin: org.gradle.tooling.BuildException: Could not execute build using Gradle distribution 'file:/Data/github/byte-buddy/byte-buddy-gradle-plugin/gradle/4.5/gradle-4.5-bin.zip'. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :byte-buddy-gradle-plugin
```

Is this bad? And can it be ignored?

OSX 10.12.6

**Comment by raphw** [comment] 2019-01-28 08:48
I experience the same issue on my CI servers which is why I do not build the plugin there. It is however annoying me and I wish I would find out what the problem is as this used to work but I cannot reproduce the problem locally.

I assume that there is something wrong with the Maven-to-Gradle integration. If you have a chance to debug this, I would be very grateful. Otherwise, this is not a problem to worry about.

**Comment by AnEmortalKid** [comment] 2019-02-05 19:34
Worked for me:
```
[INFO] --- maven-antrun-plugin:1.8:run (copy-jar) @ byte-buddy-gradle-plugin ---
[INFO] Executing tasks

main:
     [copy] Copying 1 file to /Users/jm034719/workspaces/byte-buddy/byte-buddy-gradle-plugin/target
[INFO] Executed tasks
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Byte Buddy (parent) 1.9.10-SNAPSHOT:
[INFO] 
[INFO] Byte Buddy (parent) ................................ SUCCESS [ 10.247 s]
[INFO] Byte Buddy Java agent .............................. SUCCESS [ 18.109 s]
[INFO] Byte Buddy (with dependencies) ..................... SUCCESS [ 59.955 s]
[INFO] Byte Buddy (without dependencies) .................. SUCCESS [  4.170 s]
[INFO] Byte Buddy benchmarks .............................. SUCCESS [  5.697 s]
[INFO] Byte Buddy for Android ............................. SUCCESS [  4.367 s]
[INFO] Byte Buddy (Maven plugin) .......................... SUCCESS [  8.026 s]
[INFO] Byte Buddy (Gradle plugin) ......................... SUCCESS [ 42.035 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:32 min
[INFO] Finished at: 2019-02-05T13:33:40-06:00
[INFO] ------------------------------------------------------------------------
```

Below are tool versions (this might help us track it down)

```
 mvn -v
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T13:41:47-05:00)
Maven home: /usr/local/Cellar/maven/3.6.0/libexec
Java version: 1.8.0_162, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre
```

```
java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
```

```
gradle -v
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/usr/local/Cellar/gradle/4.8.1/libexec/lib/groovy-all-2.4.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

------------------------------------------------------------
Gradle 4.8.1
------------------------------------------------------------

Build time:   2018-06-21 07:53:06 UTC
Revision:     0abdea078047b12df42e7750ccba34d69b516a22

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          10 ("Oracle Corporation" 10+46)
OS:           Mac OS X 10.13.6 x86_64
```

**Comment by raphw** [comment] 2019-07-30 21:42
This issue should be fixed, I do now use the Maven exec plugin and discriminate on JDK version for the Gradle version being used.

**Closed by raphw** 2019-07-30 21:42 UTC
Labels: build
