### ISSUE TITLE
Garbage collection pressure created by Method.getParameters()

### ISSUE THREAD

**Issue by dsyer** [raphw/byte-buddy#515] opened 2018-08-10 08:39 UTC
I see that `Method.getParameters()` is implemented internally in the JDK as a `clone()` and this generates a lot of garbage collection pressure with Hibernate because of the way that Byte Buddy iterates over method parameters (I think), and also because Hibernate adds static methods to entity proxies with large numbers of parameters.

The offending code path is 

```
ParameterList$ForLoadedExecutable$OfMethod.get(int) line: 320	
ParameterList$ForLoadedExecutable$OfMethod.get(int) line: 307	
AbstractList$Itr.next() line: 358	
TargetMethodAnnotationDrivenBinder.compile(MethodDescription) line: 64	
MethodDelegation$ImplementationDelegate$ForStaticMethod.of(MethodList<?>, MethodDelegationBinder) line: 759	
MethodDelegation$WithCustomProperties.to(TypeDescription) line: 1223	
MethodDelegation$WithCustomProperties.to(Class<?>) line: 1204	
MethodDelegation.to(Class<?>) line: 255	
```

the problem being that iterating over all method parameters causes a new instance of `ParameterDescription.ForLoadedParameter.OfMethod` to be created for each parameter, and each one takes a copy of _all_ the parameter types via the JDK `Method` implementation. I imagine the iteration could be optimized.

I am using Flight Recorder to look at garbage collection pressure which slows down application startup for large (in this case pathological) apps - i.e. with large numbers of entities. I think if it could be optimized here it would have a beneficial effect on less pathological apps.

**Comment by raphw** [comment] 2018-08-10 08:51
Thanks for reporting. `MethodDelegation` instances are quite expensive by themselves as they process metadata which is another weak spot in the JVM performance-wise. I will have a look how this is used in Hibernate, the instances are immutable and can be reused.

**Comment by dsyer** [comment] 2018-08-10 11:00
You are welcome.

Another source of GC pressure is the internal implementation of `ParameterDescription.ForLoadedParameter.OfMethod`. For instance `getDeclaredAnnotations()` re-parses the annotations of the whole method for every parameter, I think. And `getType()` clones the parameter types again. The former is definitely visible in the Flight Recorder as a creator of `char[]` in the `ConstantPool`, while the latter is not yet visible, but might surface if we are optimizing other things. I can open a separate issue about that if you prefer.

**Comment by gsmet** [comment] 2018-08-10 16:44
@dsyer do you have the rest of the stacktrace, the Hibernate part?

**Comment by gsmet** [comment] 2018-08-10 16:55
From what I can see, it's only used when initializing the proxy classes so it shouldn't be in the hot path, once started.

We could optimize things by making these `MethodDelegation.of()` elements static but, unfortunately, with the current architecture, these proxy factories are long lived and I'm not sure I would want to keep these objects around.

@raphw do you know if these objects consumes a lot of memory?

**Comment by gsmet** [comment] 2018-08-10 16:58
@raphw btw, we had to do this optimization in Hibernate Validator too. We pass the `Method.getParameters()` result along with the `executable` in a couple of methods as calling `getParameters()` was too slow.

I think it would be a nice thing to do anyway in ByteBuddy.

**Comment by dsyer** [comment] 2018-08-10 17:10
@gsmet Flight Recorder doesn't make it easy to copy complete stack traces. It comes from `org.hibernate.proxy.pojo.bytebuddy.ByteBuddyProxyFactory.lambda$buildProxy$1(Class, Class[])`. I can grab a stack from the debugger in the IDE, but it's possible this was a different code path than the one that slows us down with GC pressure:

```
ParameterList$ForLoadedExecutable$OfMethod.get(int) line: 320	
ParameterList$ForLoadedExecutable$OfMethod.get(int) line: 307	
AbstractList$Itr.next() line: 358	
TargetMethodAnnotationDrivenBinder.compile(MethodDescription) line: 64	
MethodDelegation$ImplementationDelegate$ForStaticMethod.of(MethodList<?>, MethodDelegationBinder) line: 759	
MethodDelegation$WithCustomProperties.to(TypeDescription) line: 1223	
MethodDelegation$WithCustomProperties.to(Class<?>) line: 1204	
MethodDelegation.to(Class<?>) line: 255	
ByteBuddyProxyFactory.lambda$buildProxy$1(Class, Class[]) line: 107	
121483686.call() line: not available	
TypeCache$WithInlineExpunction<S>(TypeCache<T>).findOrInsert(ClassLoader, T, Callable<Class<?>>) line: 137	
TypeCache$WithInlineExpunction<S>.findOrInsert(ClassLoader, S, Callable<Class<?>>) line: 344	
TypeCache$WithInlineExpunction<S>(TypeCache<T>).findOrInsert(ClassLoader, T, Callable<Class<?>>, Object) line: 159	
TypeCache$WithInlineExpunction<S>.findOrInsert(ClassLoader, S, Callable<Class<?>>, Object) line: 353	
ByteBuddyProxyFactory.buildProxy(Class, Class[]) line: 100	
ByteBuddyProxyFactory.postInstantiate(String, Class, Set<Class>, Method, Method, CompositeType) line: 78	
PojoEntityTuplizer$1.run() line: 167	
PojoEntityTuplizer$1.run() line: 162	
PojoEntityTuplizer.buildProxyFactory(PersistentClass, Getter, Setter) line: 186	
PojoEntityTuplizer(AbstractEntityTuplizer).<init>(EntityMetamodel, PersistentClass) line: 156	
PojoEntityTuplizer.<init>(EntityMetamodel, PersistentClass) line: 60	
NativeConstructorAccessorImpl.newInstance0(Constructor<?>, Object[]) line: not available [native method]	
NativeConstructorAccessorImpl.newInstance(Object[]) line: 62	
DelegatingConstructorAccessorImpl.newInstance(Object[]) line: 45	
Constructor<T>.newInstance(Object...) line: 423	
EntityTuplizerFactory.constructTuplizer(Class<EntityTuplizer>, EntityMetamodel, PersistentClass) line: 88	
EntityTuplizerFactory.constructDefaultTuplizer(EntityMode, EntityMetamodel, PersistentClass) line: 116	
EntityMetamodel.<init>(PersistentClass, EntityPersister, SessionFactoryImplementor) line: 382	
SingleTableEntityPersister(AbstractEntityPersister).<init>(PersistentClass, EntityDataAccess, NaturalIdDataAccess, PersisterCreationContext) line: 551	
SingleTableEntityPersister.<init>(PersistentClass, EntityDataAccess, NaturalIdDataAccess, PersisterCreationContext) line: 124	
NativeConstructorAccessorImpl.newInstance0(Constructor<?>, Object[]) line: not available [native method]	
NativeConstructorAccessorImpl.newInstance(Object[]) line: 62	
DelegatingConstructorAccessorImpl.newInstance(Object[]) line: 45	
Constructor<T>.newInstance(Object...) line: 423	
PersisterFactoryImpl.createEntityPersister(Class<EntityPersister>, PersistentClass, EntityDataAccess, NaturalIdDataAccess, PersisterCreationContext) line: 96	
PersisterFactoryImpl.createEntityPersister(PersistentClass, EntityDataAccess, NaturalIdDataAccess, PersisterCreationContext) line: 77	
MetamodelImpl.initialize(MetadataImplementor, JpaMetaModelPopulationSetting) line: 154	
SessionFactoryImpl.<init>(BootstrapContext, MetadataImplementor, SessionFactoryOptions) line: 295	
SessionFactoryBuilderImpl.build() line: 467	
EntityManagerFactoryBuilderImpl.build() line: 939	
...
```

I am using Hibernate 5.3.3.

**Comment by raphw** [comment] 2018-08-10 17:15
I'll definitely look into optimizing is, the problem is however that I can only cache these instances for every instance of a method description that is created for each method delegation.

The delegation instances are not too big, they keep a reference to a single method instance at best.

**Comment by gsmet** [comment] 2018-08-13 10:31
@raphw I think a good first step from the ByteBuddy POV is to avoid calling `Method#getParameters()` more than once per method.

I'll change our implementation to avoid creating a new method delegation per proxy class.

**Comment by gsmet** [comment] 2018-08-13 14:51
@dsyer I pushed a commit to improve the situation on our end. It will be part of 5.3.5.Final I plan to release tomorrow afternoon.

Thanks for raising the issue.

**Comment by olivergierke** [comment] 2018-08-14 06:02
Looks like there are [no snapshots available for 5.3.5](https://repository.jboss.org/nexus/content/repositories/public/org/hibernate/hibernate-core/). Is it worth fixing that so that we could run tests against the binaries before they're released?

**Comment by gsmet** [comment] 2018-08-14 11:30
@olivergierke publication of the 5.3.5-SNAPSHOT should be OK now.

**Comment by olivergierke** [comment] 2018-08-14 11:39
Thanks, Guillaume, appreciated and builds updated. Looking good, no regressions found on our side.

**Comment by raphw** [comment] 2018-08-31 21:10
I added a new build plugin to Byte Buddy that caches method return values on an instance. This is now done for all annotations by classes, methods and fields and for declared members of classes. Completed on master.

**Closed by raphw** 2018-08-31 21:10 UTC
Labels: performance
