### ISSUE TITLE
[Android] ClassCastException: AnnotationDescription[] cannot be cast to AnnotationDescription

### ISSUE THREAD

**Issue by tmurakami** [raphw/byte-buddy#179] opened 2016-09-07 22:52 UTC
- byte-buddy-android 1.4.22
- emulator64-x86: api 17, 19, 21 and 24

I'm facing this issue while running my test code on Android emulators.

Here is the stacktrace:
```
java.lang.ClassCastException: net.bytebuddy.description.annotation.AnnotationDescription[] cannot be cast to net.bytebuddy.description.annotation.AnnotationDescription
at net.bytebuddy.implementation.attribute.AnnotationAppender$Default.apply(AnnotationAppender.java:312)
at net.bytebuddy.implementation.attribute.AnnotationAppender$Default.handle(AnnotationAppender.java:296)
at net.bytebuddy.implementation.attribute.AnnotationAppender$Default.doAppend(AnnotationAppender.java:355)
at net.bytebuddy.implementation.attribute.AnnotationAppender$Default.append(AnnotationAppender.java:334)
at net.bytebuddy.implementation.attribute.MethodAttributeAppender$Explicit.apply(MethodAttributeAppender.java:301)
at net.bytebuddy.implementation.attribute.MethodAttributeAppender$Compound.apply(MethodAttributeAppender.java:490)
at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:582)
at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:518)
at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:3802)
at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1618)
at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:172)
at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:153)
at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2568)
at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2670)
at com.example.myapp.MyTest.testAnnotate(MyTest.java:43)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:198)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:183)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:560)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
```

The code is as follows:
```java
package com.example.myapp;

import android.content.Context;
import android.test.AndroidTestCase;

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.ClassFileVersion;
import net.bytebuddy.android.AndroidClassLoadingStrategy;
import net.bytebuddy.description.annotation.AnnotationDescription;
import net.bytebuddy.implementation.StubMethod;
import net.bytebuddy.matcher.ElementMatchers;

import java.io.File;
import java.lang.annotation.Annotation;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.reflect.Method;

public class MyTest extends AndroidTestCase {

    @Retention(RetentionPolicy.RUNTIME)
    public @interface A1 {
    }

    @Retention(RetentionPolicy.RUNTIME)
    public @interface A2 {
        A1[] value() default {};
    }

    public interface I {
        void doIt();
    }

    public void testAnnotate() throws NoSuchMethodException {
        File dir = getContext().getDir("byteBuddy", Context.MODE_PRIVATE);
        Class<? extends Annotation> annotationType = A2.class;
        Class<?> c = new ByteBuddy()
                .with(ClassFileVersion.JAVA_V6)
                .subclass(I.class)
                .method(ElementMatchers.named("doIt"))
                .intercept(StubMethod.INSTANCE)
                .annotateMethod(AnnotationDescription.Builder.ofType(annotationType).build())
                .make()
                .load(getClass().getClassLoader(), new AndroidClassLoadingStrategy(dir))
                .getLoaded();
        Method method = c.getDeclaredMethod("doIt");
        assertEquals(annotationType, method.getDeclaredAnnotations()[0].annotationType());
    }

}
```

**Comment by raphw** [comment] 2016-09-09 10:00
This is a really strange bug. I do not currently have an Android SDK installed but I do not understand how the emulator breaks this where it runs without problem. Are you using the latest version?

Could you set a break point where the exception is thrown and check the values? Is it an empty array for `A1[] value`?

**Comment by tmurakami** [comment] 2016-09-09 11:09
> Are you using the latest version?

Yes. I'm using the latest android sdk.

My environment:

- Ubuntu 16.04
- OpenJdk 1.8.0_91
- Android Studio 2.2 RC
- Android SDK Tools 25.2.2

> Is it an empty array for A1[] value?

Yes. The length of this array is zero.
![screenshot from 2016-09-09 19-59-52](https://cloud.githubusercontent.com/assets/2504717/18385060/33f1cf88-76c9-11e6-9cf7-c9f49ad0819f.png)

**Comment by raphw** [comment] 2016-09-09 11:23
Can you share your test project?

**Comment by tmurakami** [comment] 2016-09-09 11:32
[ByteBuddyAndroid-ClassCastException.zip](https://github.com/raphw/byte-buddy/files/463847/ByteBuddyAndroid-ClassCastException.zip)

**Comment by raphw** [comment] 2016-09-09 12:54
I cannot reproduce this. The only possibility, that I see is that there is a bug in the Android SDK. Can you check:

```java
assert A1[].class.isAnnotation() == false;
```

This is required by the JLS but it seems like it returns true on your system.

**Comment by tmurakami** [comment] 2016-09-09 13:24
> This is required by the JLS but it seems like it returns true on your system.

Yes. A1[].class.isAnnotation() == true on Android...

Will you support Android?
![screenshot from 2016-09-09 22-23-31](https://cloud.githubusercontent.com/assets/2504717/18388324/2999a1b0-76dc-11e6-9ad4-a953251d51c3.png)

**Comment by raphw** [comment] 2016-09-09 13:28
I now switched the checks around which should fix it. I will try to make a release next week. Please report this as a bug to Android, this is a really bad bug in their software.

**Comment by tmurakami** [comment] 2016-09-09 14:09
> I will try to make a release next week.

Thank you!

> Please report this as a bug to Android, this is a really bad bug in their software.

I have just reported.
https://code.google.com/p/android/issues/detail?id=222104

**Comment by raphw** [comment] 2016-09-11 20:02
Fixed on master.

**Closed by raphw** 2016-09-11 20:02 UTC
Labels: Android
