### ISSUE TITLE
ExecutingTransformer transform consume too much time when execute slf4j's LoggerFactory.getLogger

### ISSUE THREAD

**Issue by jackychee** [raphw/byte-buddy#433] opened 2018-04-02 06:37 UTC

**Comment by raphw** [comment] 2018-04-02 06:38
What do you mean by that? Can you explain what you are doing and why this consumes too much time?

**Comment by jackychee** [comment] 2018-04-02 06:39
![bb-consume-time](https://user-images.githubusercontent.com/11421069/38186061-a211c696-3683-11e8-8fd7-359237b5fce1.png)

**Comment by jackychee** [comment] 2018-04-02 06:44
Hi, i use AgentBuilder to transform class before jvm load it. In my project, i transformed log4j2‘s Logger class, that will cause bytebuddy consume too much time.

**Comment by jackychee** [comment] 2018-04-02 06:48
oh,  bytebuddy's version is 1.7.11

**Comment by raphw** [comment] 2018-04-02 06:50
Transformation is a rather expensive operation but it is only applied once. I do not think that there is much one can do but you could simplify your agent, for example, you can choose to not analyze the call graph of the instrumented class by registering a noop method graph compiler if you do not require this information.

**Comment by jackychee** [comment] 2018-04-02 07:02
I'm confused about that the problem only occurred when i transformed log4j2' logger class. by the way, if i register a noop method graph compiler, Can i get type and method info from TypeDescrition and MethodDescrition?

**Comment by raphw** [comment] 2018-04-02 07:04
Yes, but Byte Buddy will not attempt to resolve methods declared by super types.

About the time consumption: Are you using SLF4j in your agent? Maybe you are triggering some form of circularity.

**Comment by jackychee** [comment] 2018-04-02 07:08
Yes, my agent dependent some artifact which will use SLF4J.

**Comment by raphw** [comment] 2018-04-02 18:10
Could you try to rip out the slf4j dependency from your agent to try it? If other classes do not take that long, I doubt that it is the method graph compiler. You can provide an agent builder with a Byte Buddy instance where you set a custom compiler if you want to try out anyways.

**Comment by jackychee** [comment] 2018-04-03 02:04
OK, i will rip out slf4j dependency and try again. And i will give you a demo which will reappear the problem i  encountered later.

**Comment by jackychee** [comment] 2018-04-03 06:33
Hi, raphw, here is my agent demo https://github.com/jackychee/agent. 
In order to run the demo, you should package the project, set another project (for example B project)'s  -javaagent parameter with it, and run B project finally.
In Agent.class, if i don't comment  SLF4JLogger.printMsg(), that will cause B project start very slow, about 110s。

**Comment by raphw** [comment] 2018-04-03 07:29
I tried on a simple project that uses SLF4J and I cannot reproduce the slow project start. Could you also give me a sample project that reproduces this issue?

Also, could you try updating to Byte Buddy 1.8.3? I fixed some performance regressions in the 1.8.* releases.

**Comment by jackychee** [comment] 2018-04-03 07:50
Did you use my agent demo? 1. package my agent demo, you can find a agent-1.0.jar under target directory. 2. add -javaagent:path/to/agent-1.0.jar  to what ever java project.  3. start java project.

**Comment by raphw** [comment] 2018-04-03 13:13
This is what I have tried but the start up takes a bit under a second. Did you try the update that I suggested?

**Comment by jackychee** [comment] 2018-04-04 01:50
I updated bytebuddy's version to 1.8.3, and that make no changes. I will run my agent demo in other machine to see how it going.

**Comment by jackychee** [comment] 2018-04-04 02:57
![bb-ubuntu](https://user-images.githubusercontent.com/11421069/38286220-bea94d3c-37f6-11e8-84d9-a8fe26ee3196.png)
I run agent-test project in ubuntu 16.04 LTS, java version "1.8.0_112", and agent-test start up 159s

**Comment by raphw** [comment] 2018-04-08 19:37
I recreated this example: http://www.baeldung.com/slf4j-with-log4j2-logback and could still not reproduce this.

**Comment by jackychee** [comment] 2018-04-09 01:50
I'm a little careless that i wan't give you my agent-test project, forgive me. here is my agent-test project https://github.com/jackychee/agent-test .

**Comment by raphw** [comment] 2018-04-09 20:38
I tried your project and it runs in less then a second. Are you sure that you do not have a file lock or something that slows things down?

**Comment by testn** [comment] 2018-04-12 18:26
@raphw which version of JDK are you using? I can replicate the problem

**Comment by raphw** [comment] 2018-04-13 19:56
You are right, I have used a JDK 10 to run the example but with a JDK 8, I can reproduce the lag.

**Comment by raphw** [comment] 2018-04-13 20:32
Alright, the problem is that the performance of `LinkedHashMap` degrades after a certain amount of entries. The Log4j logger declares around 500 methods and I have never tested for this. I will need to rework parts of the method graph compiler to better handle this. Fortunately, your simple agent can use an optimization where the method graph can be extracted much easier. Define your agent to use:

```
new ByteBuddy().with(MethodGraph.Compiler.ForDeclaredMethods.INSTANCE)
```

**Comment by raphw** [comment] 2018-04-13 20:40
This is a tricky one, Byte Buddy runs in a performance issue here that is resolved by JVM improvements in later versions of Java but for Java 8 and before, the only solution would be to replace the `LinkedHashMap` as a data structure with something tailored to this use case. The problem is that, upon copying, the hash code of every key is recomputed what is fairly inefficient. Maybe adding a wrapper object that caches the key can help.

**Comment by jackychee** [comment] 2018-04-14 02:53
Thank @raphw @testn

**Closed** 2018-04-14 02:55 UTC
Labels: performance, question

**Comment by testn** [comment] 2018-04-14 02:57
@raphw what is the reason behind the use of Harmonized class. The implementation looks pretty inefficient and I don't seem to understand how it is used.

**Comment by raphw** [comment] 2018-04-14 07:13
It is a key for a method that is gradually expanded by discovering more bridges up the class hierarchy.

There is probably quite some potential performance improvement. I will need to have a look.

**Comment by jackychee** [comment] 2018-04-16 02:28
Thanks for your expertise and lucid explanation of the cause, @raphw
