### ISSUE TITLE
IllegalAccessException JDK17 on package-private parent class

### ISSUE THREAD

**Issue by milossamek** [raphw/byte-buddy#1251] opened 2022-05-16 06:46 UTC
Hello, currently with the usage of JDK 11, (probably?) JDK 17 we are facing an `IllegalAccessException` when using ByteBuddyProxy instanced classes with `package private parent classes`.

For now I was not able to isolate the exception into the unit tests. Exception message:
```
java.lang.IllegalAccessException: class com.fg.form.core.context.lookup.aop.ResultCachingAdvice cannot access a member of class com.fg.cps.eshop.statistics.web.dataProvider.AbstractStatsDataSource with modifiers "public"
```

The important parts on this flow are
- we have a package abstract private class, which is extended
  ```
  abstract class AbstractStatsDataSource<T, SELF_TYPE extends AbstractStatsDataSource<T, SELF_TYPE>> extends AbstractDataProvider<SELF_TYPE> implements ChartDataSource {
- then we have an implementation
  ```
  public class AverageOrderStatsDataSource extends AbstractStatsDataSource<BigDecimal, OrderAmountStatsDataSource> {
  ```
- we have a multilevel proxying
  - first we are creating a proxy instance via ByteBuddy
  - second time proxying, we are updating an instance with custom `advices` (Caching advice)
- when I remove the multilevel proxying (instance created only for Proxy without advices), the method is callable.
- when I create multilevel proxy in the unit tests, the method is callable
- when I update `AbstractStatsDataSource` as public, the method is callable 

With usage of JDK8 everything is working perfectly, but after migration to JDK11, we are facing this.

Do you have some ideas, hints? What could help us to solve this issue?

Example of problem:
- first is existing instance of chart data source (proxied one)
- second is manually created one
![image](https://user-images.githubusercontent.com/40331603/168534951-844990d7-059c-43bf-a6e5-9120106566ce.png)

**Comment by milossamek** [comment] 2022-05-17 06:01
Hello Rafael, thanks for the fast asnswer.

I have been already using the logic as you mentioned in past in the article http://mydailyjava.blogspot.com/2018/04/jdk-11-and-proxies-in-world-past.html 

Now I have updated the logic as you mentioned using `withFallback`, but the result is the same. It still ends on the "public" modifier.

Calling method with the lookup and the "instance" is called in the same `package` as the generated class.
`
 ClassLoadingStrategy.UsingLookup.withFallback(MethodHandles::lookup);
`

**Comment by raphw** [comment] 2022-05-17 07:05
that's strange. Can you post a small reproducer?

**Comment by milossamek** [comment] 2022-05-17 07:34
as mentioned before I was not able to prepare one inside the tests, but I will try my best.

Will keep you posted.

**Comment by novoj** [comment] 2022-05-30 16:17
The problem was not connected with the ByteBuddy but rather with our implementation that called method on the delegate without ensuring, that method has open access to the method (via. `.setAccessible(true)`). Due to complexity involved in proxies we got lost and attributed the problem to JDK version / ByteBuddy. But later we found that the problem occurs even on JDK8 and focused our attention to a correct place.

I'm terribly sorry for stealing your precious time @raphw and thank you. @milossamek we can close the issue (if you can as an author) now.

**Comment by milossamek** [comment] 2022-05-31 06:43
As mentioned by @novoj, sorry for the false-positive report.

Anyway thanks for your support.

**Closed** 2022-05-31 06:42 UTC
Labels: question
