### ISSUE TITLE
Lazily resolve type of @Advice.This annotated parameter

### ISSUE THREAD

**Issue by felixbarny** [raphw/byte-buddy#290] opened 2017-04-09 16:54 UTC
Disclaimer: this occurs using 1.5.7. I don't know if this maybe is already fixed in the latest version.

It seems like the types of `@Advice.This` annotated parameters are resolved even if the type matcher does not match anything.

This is problematic if you're referencing a type which is optional i.e. might not be in the class path leading to a `NoClassDefFoundError`.

The concrete problem is in [SpringRestTemplateContextPropagatingTransformer](https://github.com/stagemonitor/stagemonitor/blob/767b5eba6ae7ade72aa2eaa47afeb788b3d592d2/stagemonitor-web/src/main/java/org/stagemonitor/web/tracing/SpringRestTemplateContextPropagatingTransformer.java#L43-L43) which adds a B3 header injecting interceptor to Spring's `RestTemplate`. This class obviously is not always present. [Here](https://travis-ci.org/stagemonitor/stagemonitor-integration-tests/jobs/219993239#L1077) is a travis build which tries to start a hibernate application on JBoss but fails. The important bit is:

```
15:06:06,877 ERROR [org.stagemonitor.core.Stagemonitor] (MSC service thread 1-1) org/springframework/http/client/support/InterceptingHttpAccessor: java.lang.NoClassDefFoundError: org/springframework/http/client/support/InterceptingHttpAccessor
	at java.lang.Class.getDeclaredMethods0(Native Method) [rt.jar:1.7.0_76]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2615) [rt.jar:1.7.0_76]
	at java.lang.Class.getDeclaredMethods(Class.java:1860) [rt.jar:1.7.0_76]
	at net.bytebuddy.description.method.MethodList$ForLoadedMethods.<init>(MethodList.java:90)
	at net.bytebuddy.description.type.TypeDescription$ForLoadedType.getDeclaredMethods(TypeDescription.java:7826)
	at net.bytebuddy.asm.Advice.to(Advice.java:302)
	at net.bytebuddy.asm.Advice$WithCustomMapping.to(Advice.java:9410)
	at net.bytebuddy.asm.Advice$WithCustomMapping.to(Advice.java:9395)
	at net.bytebuddy.asm.Advice$WithCustomMapping.to(Advice.java:9384)
	at org.stagemonitor.core.instrument.StagemonitorByteBuddyTransformer$2.<init>(StagemonitorByteBuddyTransformer.java:103)
```

A simple workaround would be to use `Object` as the parameter type and to add a type cast in the method. Another workaround would be to check the presence of the type and only register the transformer if it is present. But that would cause the class to be loaded so that it has to be retransformed which is way more costly. (BTW: do you know of a method to check the presence of a class without loading it?)

So even if workarounds exist it would be quite nice if Byte Buddy would resolve the types lazily to avoid a `NoClassDefFoundError`

**Comment by raphw** [comment] 2017-04-10 06:25
The types are not resolved by Byte Buddy but by the reflection API upon calling any of the `getDeclared[Methods|Fields]` methods which resolves all signature types eagerly. Optional types are no native concept that the JVM allows and therefore, the error is thrown.

The only way to avoid this would be to use a publicly known type (worst case `Object`) in the signature and to cast the type within the method.

**Comment by felixbarny** [comment] 2017-04-10 06:36
But Byte Buddy does call `getDeclaredMethods` so it indirectly resolves the types. Maybe it would be possible to lazily call `getDeclaredMethods`? Otherwise a hint on `@Advice.This` would be helpful.

**Comment by raphw** [comment] 2017-04-10 06:48
The call is part of creating the `Advice` class. The initialization is not cheap, therefore, the resolution is done eagerly to create an immutable `Advice` object. I think that you are currently caching these instances what makes sense for performance but triggers these errors.

Maybe you can just catch the error and handle this as an indicator for the missing class?

**Comment by felixbarny** [comment] 2017-04-10 06:52
> Maybe you can just catch the error and handle this as an indicator for the missing class?

+1

**Comment by CodingFabian** [comment] 2017-04-10 07:34
what we do is to use an element matcher which verifies that all types used in the advice are visible by the class that is being adviced.

but that is a bit cumbersome and error prone. Until now I did not have a better idea. Maybe this problem could be generalized into something that BB could verify before applying an advice.

**Comment by raphw** [comment] 2017-04-10 14:20
The problem is that Byte Buddy does not have a mechanism to check if signature types exist. The only way to retreive the information (for loaded types) is to use the reflection API which does not give you a "soft access" to check if types can actually be loaded. Byte Buddy cannot do much more than to crash and burn. Therefore, the types in question need to be named explicitly and seperatly from the method signature. This is unfortunate but there is no good way around it.

**Closed by raphw** 2017-04-10 14:20 UTC
Labels: question
