### ISSUE TITLE
can i get some annotation's value but not visit this annotation method

### ISSUE THREAD

**Issue by dragontree101** [raphw/byte-buddy#160] opened 2016-07-27 05:02 UTC
if my code is 
```
@TestAnnotation(value = "test123")
public void test() {...}

public void foo() {...}
```
can i to get this ```@TestAnnotation``` value when i call foo() function?

first i want to get some annotation's value, and save it, and then i want to get this annotation's value when call other method,  i don't know how to do this.  

thanks

**Comment by raphw** [comment] 2016-07-27 07:32
Are you using a `MethodDelegation` or are you using `Advice`? You can always access annotations by using the `@Origin` annotation with a `Method` when using the former. From the `Advice` component, you can use a `Advice.withCustomBinding()` to inject a constant value that you read from the annotation during class manipulation time.

**Comment by dragontree101** [comment] 2016-07-27 08:06
i use ```Advice```   i want to get others method's annotation,

**Comment by raphw** [comment] 2016-07-27 08:41
You can create a `DynamicValue` for some annotation where you return:

```java
instrumentedValue.getDeclaringType()
    .getDeclaredMethods()
    .filter(named("test"))
    .getOnly()
    .getDeclaredAnnotations()
    .ofType(TestAnnotation.class)
    .loadSilent()
    .value();
```

If you bind this annotation to some dynamic annotation `MyAnnotation`, you can access it by:

```java
@MyAnnotation String value
```

from your `Advice` method.

**Comment by raphw** [comment] 2016-07-27 21:52
I am closing this ticket. I can reopen it, if the issue is not resolved.

**Closed by raphw** 2016-07-27 21:52 UTC
Labels: question
