### ISSUE TITLE
Issue with bridging method?

### ISSUE THREAD

**Issue by J-cztery** [raphw/byte-buddy#656] opened 2019-05-19 14:37 UTC
byte-buddy-1.9.12
```
public interface MyGenericConsumer<T> {
        void accept(T obj);
}
public static class GenericConsumerReproducer implements MyGenericConsumer<String> {
        public void accept(String obj) {
            
        }
}

@Test public void reproducer() throws Exception {

        new ByteBuddy()
                                                     .subclass(GenericConsumerReproducer.class)
                                                     .name("zupa_buraczkowa")
                                                         .defineMethod("accept", Void.TYPE, Modifier.PUBLIC)
                                                             .withParameters(Arrays.asList(Object.class))
                                                             .intercept(SuperMethodCall.INSTANCE)
                                                     .make()
                                                     .load(GenericConsumerReproducer.class.getClassLoader())
                                                     .getLoaded()
                                                     .newInstance();
 
    }
```
Results in : 
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    zupa_buraczkowa.accept(Ljava/lang/Object;)V @2: invokespecial
  Reason:
    Type 'java/lang/Object' (current frame, stack[1]) is not assignable to 'java/lang/String'
  Current Frame:
    bci: @2
    flags: { }
    locals: { 'zupa_buraczkowa', 'java/lang/Object' }
    stack: { 'zupa_buraczkowa', 'java/lang/Object' }
  Bytecode:
    0000000: 2a2b b700 09b1                         

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3110)
	at java.base/java.lang.Class.getConstructor0(Class.java:3315)
	at java.base/java.lang.Class.newInstance(Class.java:530)
But if GenericConsumerReproducer does not implement MyGenericConsumer<String>, everything works fine. 
What is happening here? I think  when MyGenericConsumer<String> is implemented there is a bridging method generated:
```
void accept(Object obj) {
    accept((String)obj);
} 
```
but i should still be ok to define and override void accept(Object ob) and call into super, no?

EDIT: updated bridging method.

**Comment by raphw** [comment] 2019-05-22 22:12
I think Byte Buddy is missing the fact that the method overrides a generic method in a raw state but the method graph compiler assigns the method to the override group. If you replace the argument type with a `String`, everything should work.

Byte Buddy is not validating the method argument's assignability but should throw an exception, I will add that in the next version.

**Comment by J-cztery** [comment] 2019-05-23 04:53
Hmm, isn't it because ByteBudy does not find the bridging method void accept(Object obj) and uses void accept(String) instead?

I think the bridging methods have Volatile modifier set. Does ByteBuddy exclude them in its search for candidates?

**Comment by raphw** [comment] 2019-05-24 18:54
The problem is that Byte Buddy finds the bridged super method (not the bridge that must not be called as it would dispatch back using a virtual call) but then assumes that the method being instrumented is more specialized then the original method defined in the sub class. Since this is not the case, the less specific types cannot be assigned to the more specific types.

I need to add some validation here, not a big issue but I need to get that right as this code is often on the hot path. In the future, you will get an exception under code generation rather then the verifier error.

**Comment by J-cztery** [comment] 2019-05-25 12:13
> If you replace the argument type with a String, everything should work.

I do not want to override void accept(String) but bridge method void accept(Object) (or both). The reproducer code i provided was a simplified extract to illustrate the problem. The method parameter types are actually obtained at run time from raw interface type. 

>I need to add some validation here, not a big issue but I need to get that right as this code is often on the hot path. In the future, you will get an exception under code generation rather then the verifier error.

This will just really put lipstick on the pig and not address the issue reported here. 

Maybe my understanding is not correct but my thinking goes: 
Given the definitions: 
```
public interface MyGenericConsumer<T> {
        void accept(T obj);
}
public class GenericConsumerReproducer implements MyGenericConsumer<String> {
        public void accept(String obj) {
            
        }
}
```

GenericConsumerReproducer after type erasure becomes: 
```
public class GenericConsumerReproducer implements MyGenericConsumer {
        public void accept(String obj) {  
        }
        public void accept(Object obj) { //This is the bridge method 
               accept((String) obj);
        }
}
```
Now what i am trying to do using ByteBuddy is generate a class: 
```
public class zupa_buraczkowa extends GenericConsumerReproducer  {
        public void accept(Object obj) { 
               super.accept(obj);
        }
}
```

Any chances that ByteBuddy will just allow me to do it?

**Comment by raphw** [comment] 2019-05-25 20:16
You can ask Byte Buddy to not locate bridges but to only consider method overrides for equivalent methods. Do so by registering a `MethodGraph.Compiler.Default.forJvmHierachy()`.

**Comment by J-cztery** [comment] 2019-05-26 12:39
>You can ask Byte Buddy to not locate bridges but to only consider method overrides for equivalent methods. Do so by registering a MethodGraph.Compiler.Default.forJvmHierachy() in the ByteBuddy instance.

Do you mean by doing : 
```
    @Test public void reproducer() throws Exception {
        new ByteBuddy().with(MethodGraph.Compiler.Default.forJVMHierarchy())
                       .subclass(GenericConsumerReproducer.class)
                       .name("zupa_buraczkowa")
                       .defineMethod("accept", Void.TYPE, Modifier.PUBLIC)
                       .withParameters(Arrays.asList(Object.class))
                       .intercept(SuperMethodCall.INSTANCE)
                       .make()
                       .load(GenericConsumerReproducer.class.getClassLoader())
                       .getLoaded()
                       .newInstance();
    }
```
?
It ends up with the same VerifyError.

I feel that there must be a simpler way of achieving what I want. What i am trying to do is to essentially create an instance of a named subclass of a given class, so that my call stacks are more descriptive than just stack frames containing methods from subclass (i care only about certain methods and they are described by an interface class). Is there a simpler way of doing it?

**Comment by raphw** [comment] 2019-07-30 21:39
Byte Buddy does now throw an exception upon discovering an illegal super method call.

I looked into what you are trying to do and by overriding the bridge and invoking its direct super method, you would only end up in an endless loop as the bridge method would only call its bridge target which is invoked virtually.

I'd suggest that you override the actual method with the correct generic type such that you touch the correct call hierarchy.

**Closed** 2019-07-31 07:42 UTC
Labels: bug
