### ISSUE TITLE
Byte buddy access to package protected class

### ISSUE THREAD

**Issue by vishwastyagi** [raphw/byte-buddy#1694] opened 2024-08-12 12:18 UTC
Hi Team,
I have a scenario where user of my application provides a jar at runtime. It is a third party jar. In my application I use classes defined in this jar. There is one class in this jar, called CI. This is package protected class in this jar file. There is another public class in this jar, Connection, whose one method create object of CI class and return that, but return type of this method is Object and hence I use reference variable of Object class to hold this returned object. So I get the object of class CI stored in the Object type reference variable.
`Object obj=connection.getCI();`

Now, using this obj and Java reflection, I access various package protected attributes and call methods of class CI(setting `setAccessbile(true)` for field and methods that I want to access). I am migrating my application to Java 17, and doing such manipulation using reflection is not allowed. I am trying to use byte buddy to handle such situation. I cannot subclass bytebuddy dynamic class with CI class, as CI is package protected, I get error like "cannot access it's superclass CI". I tried MethodDelegation.to(...), but that approach also not work. 
Please suggest some approaches I can use.

**Comment by vishwastyagi** [comment] 2024-08-12 12:25
Please note that I don't want to use reflection.

**Comment by sf-vishwastyagi** [comment] 2024-08-15 05:51
hi @raphw 
Thanks for response. My application is developed in java 8, and currently we are making changes so that code can run in java 17. We are planning to support java 8, java 11 and java 17. So, still we build our code in java 8(do mvn clean install), but we making sure that generated code can run java 17 as well, use a Java 17 runtime environment to execute the compiled code. Also, our code is not modularized, it works as a part of the UNNAMED module. Are there no options available in byte buddy to resolve the problem asked in previous(above) question?

**Comment by raphw** [comment] 2024-08-15 20:48
It does not relate to the Java version. If you cannot express it in the Java language, it cannot be done in Byte Buddy either.

**Comment by sf-vishwastyagi** [comment] 2024-08-23 04:24
thank you very much for reply. You can close this issue

**Comment by sf-vishwastyagi** [comment] 2024-09-05 11:33
Hi @raphw 
I need a help. 
I want to build a dynamic class using which can do that following :-
1. I have a third party jar which has package x.y.z.
2. create a dynamic class in x.y.z package.
3. There is already many package protected class in this package like CIPropertyInfo.class
4. In my application package, "p1", I have a class CIPropertyInfoAccessor class, where I get the object of class CIPropertyInfo and store it in Object type reference(since CIPropertyInfo is package protected class and cannot be reference outside psft.pt8.joa package).
Object ciPropertyInfoInstance = Connection.getCIPropertyInfoInstance();
5. Pass this ciPropertyInfoInstance in the newly created dynamic byte buddy class.
6. Define other methods in this newly created dynamic byte buddy class that can internally/inside calls the methods of CIPropertyInfo. Like CIPropertyInfo class has method 
public String getName(){....}. So, define method in this newly created dynamic byte buddy class "String getName(){return ciPropertyInfoInstance.getName()}". Since this  dynamic byte buddy class is inside the package x.y.z, it should be able to call methods of CIPropertyInfo class.

Could you please help me with some code snippet?

**Comment by sf-vishwastyagi** [comment] 2024-09-05 19:41
Something similar:-
public class DynamicCIPropertyInfo {
    private final CIPropertyInfo propertyInfo;

    public DynamicCIPropertyInfo(CIPropertyInfo propertyInfo) {
        this.propertyInfo = propertyInfo;
    }

    public String getName() {
            return propertyInfo.getName();
    }
}

Since I  get object of CIPropertyInfo and store it in Object reference, something below can also help

public class DynamicCIPropertyInfo {
    private final Object propertyInfo;

    public DynamicCIPropertyInfo(Object propertyInfo) {
        this.propertyInfo = propertyInfo;
    }

    public String getName() {
               Class<?> ciPropertyInfoClass = propertyInfo.getClass();
                Method method = ciPropertyInfoClass.getDeclaredMethod("getName");
                return method.invoke(ciPropertyInfoInstance);
    }
}

**Comment by raphw** [comment] 2024-09-05 20:05
The problem is your anonymous class interceptor. Rather declare that interceptor as its own class with public visibility. As an anonymous class, it will not be visible to outside packages.

**Comment by sf-vishwastyagi** [comment] 2024-09-05 20:18
Hi @raphw 
Thanks for answering. But I used separate class as well:-

```
DynamicType.Unloaded<?> dynamicClass = new ByteBuddy()
                .subclass(Object.class) // The dynamic class will extend Object
                .name("x.y.z.DynamicCIPropertyInfo") // Set the package and class name
                .defineMethod("getName", String.class, Modifier.PUBLIC) // Define a method in the dynamic class
                .intercept(MethodDelegation.to(new MethodInterceptor(propertyInfo, "getName")))
                .make();
                ....
                ....
                
     public static class MethodInterceptor {
        private final Object ciPropertyInfoInstance;
        private final String methodName;
        public MethodInterceptor(Object ciPropertyInfoInstance, String methodName) {
            this.ciPropertyInfoInstance = ciPropertyInfoInstance;
            this.methodName = methodName;
        }
        public Object getName() {
            try {
                // Use reflection to call the method on CIPropertyInfo
                Method method = ciPropertyInfoInstance.getClass().getDeclaredMethod(methodName);
                return method.invoke(ciPropertyInfoInstance);
            return getNameMethod.invoke(ciPropertyInfoInstance);
            } catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException e) {
                throw new RuntimeException(e);
            }
        }
    }
```
 When the getName() method in MethodInterceptor runs, I get error
 
 java.lang.IllegalAccessException: Class p1.CIPropertyInfoAccessor$MethodInterceptor can not access a member of class x.y.z.CIPropertyInfo with modifiers "public".

**Comment by sf-vishwastyagi** [comment] 2024-09-05 20:20
Please do share if you have some code snippet for the below points:-

1. I have a third party jar which has package x.y.z.
2. create a dynamic class in x.y.z package.
3. There is already many package protected class in this package like CIPropertyInfo.class
4. In my application package, "p1", I have a class CIPropertyInfoAccessor class, where I get the object of class CIPropertyInfo and store it in Object type reference(since CIPropertyInfo is package protected class and cannot be reference outside psft.pt8.joa package).
 Object ciPropertyInfoInstance = Connection.getCIPropertyInfoInstance();
5. Pass this ciPropertyInfoInstance in the newly created dynamic byte buddy class.
6. Define other methods in this newly created dynamic byte buddy class that can internally/inside calls the methods of CIPropertyInfo. Like CIPropertyInfo class has method
7. public String getName(){....}. So, define method in this newly created dynamic byte buddy class "String getName(){return ciPropertyInfoInstance.getName()}". Since this dynamic byte buddy class is inside the package x.y.z, it should be able to call methods of CIPropertyInfo class.

**Comment by raphw** [comment] 2024-09-06 11:52
How do you load the class? With package protection, it is also essential to load classes in the same class loader. You should therefore likely use a method handle lookup or unsafe with injection.

**Closed** 2024-09-25 21:53 UTC
Labels: question
