### ISSUE TITLE
IllegalStateException thrown by ByteBuddy when creating a dynamic type

### ISSUE THREAD

**Issue by rschmitt** [raphw/byte-buddy#1154] opened 2021-11-16 06:22 UTC
I'm getting the following stack trace:

```
    java.lang.RuntimeException: java.lang.IllegalStateException: size = 0
        at com.github.rschmitt.dynamicobject.internal.Instances.createBBProxy(Instances.java:186)
        at com.github.rschmitt.dynamicobject.internal.Instances.wrap(Instances.java:38)
        at com.github.rschmitt.dynamicobject.internal.EdnSerialization.deserialize(EdnSerialization.java:123)
        at com.github.rschmitt.dynamicobject.internal.EdnSerialization.deserialize(EdnSerialization.java:112)
        at com.github.rschmitt.dynamicobject.DynamicObject.deserialize(DynamicObject.java:108)
        at com.github.rschmitt.dynamicobject.MetadataTest.repro(MetadataTest.java:8)

        Caused by:
        java.lang.IllegalStateException: size = 0
            at net.bytebuddy.matcher.FilterableList$AbstractBase.getOnly(FilterableList.java:139)
            at net.bytebuddy.implementation.MethodCall$ArgumentLoader$ForInstance$Factory.make(MethodCall.java:1524)
            at net.bytebuddy.implementation.MethodCall$Appender.<init>(MethodCall.java:3520)
            at net.bytebuddy.implementation.MethodCall.appender(MethodCall.java:678)
            at net.bytebuddy.dynamic.scaffold.MethodRegistry$Handler$ForImplementation.compile(MethodRegistry.java:234)
            at net.bytebuddy.dynamic.scaffold.MethodRegistry$Handler$ForImplementation.compile(MethodRegistry.java:206)
            at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default$Prepared.compile(MethodRegistry.java:741)
            at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:218)
            at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:204)
            at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3659)
            at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3897)
            at com.github.rschmitt.dynamicobject.internal.Instances.createBBProxy(Instances.java:179)
            ... 5 more
```

To repro this stack trace, run:

```
git clone https://github.com/rschmitt/dynamic-object -b bytebuddy-repro
cd dynamic-object
./gradlew test --tests com.github.rschmitt.dynamicobject.MetadataTest --info
```

**Comment by raphw** [comment] 2021-11-17 21:45
You are right, this is a bug when generating a random field name which is not stable. I fixed it on master and it will be fixed in the next release.

**Comment by rschmitt** [comment] 2021-11-18 04:47
Thanks for the quick response. I tried the latest commit and now I'm getting a different error message:

```
MetadataTest > repro() STANDARD_OUT
    interface com.github.rschmitt.dynamicobject.MetadataTest$AnnotatedData: (AnnotatedData)AnnotatedData

MetadataTest > repro() FAILED
    java.lang.RuntimeException: java.lang.IllegalStateException: Duplicate field definition for public static clojure.lang.Keyword com.github.rschmitt.dynamicobject.internal.DynamicObjectInstance$ByteBuddy$cfDChIke.methodCall$7m459f3
        at com.github.rschmitt.dynamicobject.internal.Instances.createBBProxy(Instances.java:186)
        at com.github.rschmitt.dynamicobject.internal.Instances.wrap(Instances.java:38)
        at com.github.rschmitt.dynamicobject.internal.EdnSerialization.deserialize(EdnSerialization.java:123)
        at com.github.rschmitt.dynamicobject.internal.EdnSerialization.deserialize(EdnSerialization.java:112)
        at com.github.rschmitt.dynamicobject.DynamicObject.deserialize(DynamicObject.java:108)
        at com.github.rschmitt.dynamicobject.MetadataTest.repro(MetadataTest.java:8)

        Caused by:
        java.lang.IllegalStateException: Duplicate field definition for public static clojure.lang.Keyword com.github.rschmitt.dynamicobject.internal.DynamicObjectInstance$ByteBuddy$cfDChIke.methodCall$7m459f3
            at net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated(InstrumentedType.java:1573)
            at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:520)
            at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:213)
            at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:204)
            at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3659)
            at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3897)
            at com.github.rschmitt.dynamicobject.internal.Instances.createBBProxy(Instances.java:179)
            ... 5 more
```

**Comment by raphw** [comment] 2021-11-19 18:00
Darn, I have not thought of this. The stable name breaks when nesting calls, of course.

I will probably need to re-randomize the field name and make sure to include that field name in the hashCode/equals clause.

I will try a different solution!

**Comment by raphw** [comment] 2021-11-22 20:43
I went for a different approach. Hopefully, the issue is solved now.

**Closed** 2021-11-22 20:45 UTC
Labels: bug

**Comment by rschmitt** [comment] 2021-11-23 08:15
LGTM, thanks!
