### ISSUE TITLE
Get an idea of the relative cost for matching operations for an agent

### ISSUE THREAD

**Issue by tylerbenson** [raphw/byte-buddy#359] opened 2017-10-24 00:41 UTC
In https://github.com/raphw/byte-buddy/issues/322#issuecomment-315033890, you suggest that annotation matching is quite an expensive operation. For some other frameworks things like interface based matching is expensive.  Is there a description somewhere for the relative cost of the various types of matchers?  Perhaps an idea for when something is expensive under what circumstances? I'm specifically interested from the perspective of an `AgentBuilder`.

Thanks!

**Comment by raphw** [comment] 2017-10-24 07:34
I could write a book on the details but in general the performance cost is aligned to that of the Java reflection API. If you ask for a property that is resolved by the execution engine or the verifier, this property is available anyways. This is for example the type name or a type's raw type. If you request generics or annotations this is meta data that is resolved lazy and especially before Java 8, those operations are costy.

Also, when using the `TypePool.Default` implementation (when instrumenting non-loaded types), this pool is by default wrapped with a projection that resolves the name before parsing any class file if this suffices. Therefore, if you can exclude a lot of classes by a (sub)property based only on a type's name, this is of course a big optimization as Byte Buddy does not need to parse any class files or even do I/O to resolve linked class files.

**Comment by tylerbenson** [comment] 2017-10-24 21:13
Perhaps a suggestion then is to include some sort of notation in the javadocs to highlight when a particular matcher is expensive to make it easier to identify.

Thanks!

**Comment by raphw** [comment] 2017-10-24 21:35
I will consider that and surely do if I find the time. The problem is that the costs depend on a particular implementation of `TypeDescription` where a user can in theory implement custom classes. Therefore, the matcher is not really aware of the factual performance implications.

**Closed** 2017-11-01 15:55 UTC
Labels: question
