### ISSUE TITLE
IllegalArgumentException: Cannot attach undefined variable: T

### ISSUE THREAD

**Issue by felixbarny** [raphw/byte-buddy#117] opened 2016-04-25 08:36 UTC
In my [InstrumentationPerformanceTest](https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-benchmark/src/test/java/org/stagemonitor/InstrumentationPerformanceTest.java) (and in a real world project) I'm getting a lot of errors like these:

```
[main] WARN org.stagemonitor.core.instrument.ErrorLoggingListener - ERROR on transformation org.elasticsearch.gateway.MetaDataStateFormat$StateIdAndLegacyPredicate
java.lang.IllegalArgumentException: Cannot attach undefined variable: T
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.onTypeVariable(TypeDescription.java:1975)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.onTypeVariable(TypeDescription.java:1898)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfTypeVariable$Symbolic.accept(TypeDescription.java:5555)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor.onParameterizedType(TypeDescription.java:1859)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForAttachment.onParameterizedType(TypeDescription.java:1898)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfParameterizedType.accept(TypeDescription.java:5021)
	at net.bytebuddy.description.method.MethodDescription$Latent.getReceiverType(MethodDescription.java:1125)
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated(InstrumentedType.java:873)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:530)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:164)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:4931)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:5244)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:282)
	at org.elasticsearch.gateway.MetaStateService.loadGlobalState(MetaStateService.java:119)
	at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:87)
	at org.elasticsearch.gateway.GatewayMetaState.loadMetaState(GatewayMetaState.java:99)
	at org.elasticsearch.gateway.GatewayMetaState.pre20Upgrade(GatewayMetaState.java:225)
	at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:87)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:50)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:887)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
	at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:887)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
	at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:887)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:880)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:46)
	at org.elasticsearch.node.Node.<init>(Node.java:200)
	at org.elasticsearch.node.Node.<init>(Node.java:128)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:152)
	at org.stagemonitor.InstrumentationPerformanceTest.startElasticsearch(InstrumentationPerformanceTest.java:56)
	at org.stagemonitor.InstrumentationPerformanceTest.main(InstrumentationPerformanceTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by raphw** [comment] 2016-04-25 08:46
I will have a look. Again, it seems like a problem with overvalidation. Do you enable validation in production?

**Comment by felixbarny** [comment] 2016-04-25 09:10
Hi Raphael,

no, I don't enable validation in production - only in testing environments. But it's not always apparent whether such an exception is just a validation error or the transformation actually fails. Even if these are not big issues it's probably still be worth taking a look at them.

It's strange that you can't reproduce it. The current master should be fine. You executed `gradle clean instrumentationPerformanceTest`, right? But yes, they all contain the line `at net.bytebuddy.description.method.MethodDescription$Latent.getReceiverType(MethodDescription.java:1125)`

Anyway, here is the complete log: [instrumentationPerformanceTest.txt](https://github.com/raphw/byte-buddy/files/234188/instrumentationPerformanceTest.txt)

**Comment by raphw** [comment] 2016-04-25 09:15
Hi, I ran the test from IntelliJ. I just figured out that there was a null-pointer exception happening which did not apply the instrumentation but still run the test successfully. I currently build the project. Once I have a reproduction, it should hopefully be easy to fix.

If they all contain the line, I think I know what the problem is. Java 8 receiver types are a bit ill-defined. Hopefully this becomes better in Java 9 but I will fix it nevertheless.

**Comment by felixbarny** [comment] 2016-04-25 09:16
ah, yes, sorry. you have to initially execute `gradle processResources`. otherwise it can't find the dispatcher.jar

**Comment by raphw** [comment] 2016-04-25 09:18
Ok, thanks, no problem. (Maybe add an explicit check with an exception that points this out if the `getResource` method returns null?)

I just reproduced it and it is the problem that I thought it was. FYI: If you do not call `getReceiver` anywhere and if you do not enable validation, this problem has no side-effect in a production environment.

**Comment by raphw** [comment] 2016-04-25 12:40
Fixed on master.

**Closed by raphw** 2016-04-25 12:40 UTC
Labels: bug
