### ISSUE TITLE
"Override" final method with an agent

### ISSUE THREAD

**Issue by norswap** [raphw/byte-buddy#107] opened 2016-03-24 15:24 UTC
Is it possible to override a final method in a subclass, when using an agent? I know it isn't possible if dynamically subclassing. What if we assume that the parent hasn't been loaded yet? Removing the final modifier from the parent method would be in the cards.

What I unsuccessfully tried:

```
final class Agent {
    public static class A  {
        public final String test() { return "A"; }
    }
    
    public static class B extends A {}
    
    public static void premain(String arg, Instrumentation instrumentation) {
        TypePool typePool = TypePool.Default.ofClassPath();
        new AgentBuilder.Default()
            .type(isSubTypeOf(typePool.describe("Agent$B").resolve()))
            .transform((b, type, loader) ->
                b.method(named("test"))
                 .intercept(FixedValue.value("B")))
            .installOn(instrumentation);
    }
}
```
Is there a way to remove the final modifier, and does it help?
I'm interested to know whether it is possible, even if it doesn't help (I couldn't find a way myself).

Thanks!

**Comment by raphw** [comment] 2016-03-25 19:31
Hi, it is possible by removing the `final` modifier from `A`. Byte Buddy cannot do anything that is illegal by the rules of the Java virtual machine. Removing a final modifier can be done by using a `MethodTransformer`:

```java
      TypePool typePool = TypePool.Default.ofClassPath();
      new AgentBuilder.Default()
              .type(isSubTypeOf(typePool.describe("Agent$A").resolve()))
              .transform((b, type, loader) -> b.method(named("test")).intercept(SuperMethodCall.INSTANCE)
                      .transform(MethodTransformer.Simple.withModifiers(MethodManifestation.PLAIN)))
              .type(isSubTypeOf(typePool.describe("Agent$A").resolve()))
              .transform((b, type, loader) -> b.method(named("test")).intercept(FixedValue.value("B")))
              .installOn(instrumentation);
```

The problem is however that Byte Buddy would not - using the above code - understand that the `test` method is non-final when instrumenting `B` and refuse the transformation even though the other transformation did apply.

What you would need to do in addition is to implement a custom `AgentBuilder.BinaryLocator` that returns the modified classes from the class pool. This could be achieved by making the `BinaryLocator` also being a `Listener`. 

Let me think of this, I might include such a `BinaryLocator` in the next version.

**Comment by norswap** [comment] 2016-03-27 15:55
Thanks for the detailed answer.

It was more of a general question -- I struggled against not being able to do this when trying things out (mostly not understanding why it didn't work), but I don't actually need it.

By the way, is there a way to get some kind of diagnostics of byte buddy's operations? As a beginner, a few times I felt puzzled as things I expected to work didn't and I couldn't really tell what Byte Buddy's decision process was. Just some form of log would be very helpful (kind of like `make` has).

The solution you propose does seem satisfactory. The exception is perhaps when the list of classes for which the behavior should be modified is not known in advance.

**Comment by raphw** [comment] 2016-03-27 23:30
I agree with you that it should ideally be possible to view classes in their transformed view, i.e. the `A` class where the method in question is no longer final but this is difficult to achieve in the current implementation. Ideally, I would like to implement a `TypePool` where loaded classes are described by these loaded `Class` instances but this can contradict the current instrumentation if these classes circularly reference the currently instrumented class. Therefore, Byte Buddy rather manually parses byte code that is provided by the class loaders where classes always appear in their original format.

Also, as for diagnostics, I agree with you. The problem here is that Byte Buddy aims for performance what sometimes contradicts the collection of additional information that would make such debugging output meaningful. Other than `make`, Byte Buddy is executed at runtime, after all. I did however try my best to avoid obscure scenarios and added hopefully explanatory exception messages. Please bring up any specific case you experienced and I will try to make the library better.

For your last point, I believe that can be solved. In the end, you can always change your interceptor once you learn about a new class as in:

```java
public class MyInterceptor {
  static Map<Class<?>, Dispatcher> dispatchers = new HashMap<>();

  public static String intercept(@This Object instance, 
                                 @SuperCall Callable<String> zuper) throws Exception{
    Dispatcher dispatcher = dispatchers.get(instance.getClass());
    return dispatcher == null
        ? zuper.call()
        : dispatcher.dispatch();
  }
}
```

I am closing this question. Please reopen it if you have any further questions.

**Closed by raphw** 2016-03-27 23:30 UTC
Labels: question
