### ISSUE TITLE
[Q] How to remove/replace existing annotation

### ISSUE THREAD

**Issue by michelkaeser** [raphw/byte-buddy#354] opened 2017-10-05 15:33 UTC
Is there a way to replace (or remove so it can be re-added) an existing annotation from a type?

Let's say the input is:

```java
@PersistenceCapable
class X {}
```

and I want

```java
@PersistenceCapable(value="", key="")
class X {}
```

How would I do that?

A simple `annotateType` makes the annotation appear twice.

Thanks!

**Comment by raphw** [comment] 2017-10-06 08:08
It is possible but a bit tricky, there is not yet a good API for such transformations. The problem is that Byte Buddy cannot generally know if a value is represented as a default value or if it is explicitly defined but to this default value. It sounds irrellevant but as a matter of fact, it does matter for (too manny) applications.

I hopefully can add better support for this in the future. For now, using ASM is the easiest way of getting this done.

**Comment by thekingnothing** [comment] 2018-05-01 17:27
@raphw did you find a time to add API for removing annotation?

**Comment by raphw** [comment] 2018-05-01 19:05
Not yet, unfortunately. I use this issue to track the progress. With modules and the sun.misc.Unsafe cleanup, I did not had much time for features recently.

**Comment by raphw** [comment] 2019-02-04 23:17
As mentioned, it is not currently possible to remove the existing annotation. This is not currently solved fully satisfactory in Byte Buddy such that you have to reapply all annotations what means filtering out the first annotation using an *AsmClassVisitorWrapper* where the second one is picked up correctly.

**Comment by albanf** [comment] 2019-02-05 08:45
Do you have an example of a visitor which would remove that annotation (or all annotations?). At least for some use case, where you can rebuild the whole annotation or set of annotations, that would work.

**Comment by raphw** [comment] 2019-02-06 16:10
Basically, you need to implement a `MethodVisitor` that returns `null` on any annotation you want to remove. You can register such a visitor using a custom instance of `AsmVisitorWrapper`.

**Comment by raphw** [comment] 2021-07-14 19:58
Closing this in favor of https://github.com/raphw/byte-buddy/issues/917

**Closed by raphw** 2021-07-14 19:58 UTC
Labels: enhancement
