### ISSUE TITLE
missing source in sources JAR

### ISSUE THREAD

**Issue by mirabilos** [raphw/byte-buddy#783] opened 2019-11-26 19:00 UTC
The sources JAR for byte-buddy 1.10.3 does not contain any sources. This is a regression from 1.9.14 and might additionally have licence implications. It does in any case violate the requirements for uploading artifacts to the Maven Central Repository.

**Comment by raphw** [comment] 2019-11-26 19:36
That's too bad, I'll have it fixed for the next release. I do however doubt that this has license implications, the Apache license does not mention any of that, nor does any other open source license that I would know of.

**Comment by mirabilos** [comment] 2019-11-26 19:53
Hi Rafael,

>That's too bad, I'll have it fixed for the next release.

thanks. Ideally the sources JAR would also include the sources
for the shaded ASM copy.

>I do however doubt that this has license implications, the Apache
>license does not mention any of that, nor does any other open source
>license that I would know of.

The GPL but that isn’t used here, so probably not.

**Comment by raphw** [comment] 2019-11-26 21:01
GPL only says that sources must be made available on demand, I think.

**Comment by raphw** [comment] 2019-11-28 20:30
This is a very strange problem. When building, the sources jar in the target folder contains all shaded sources but the jar file uploaded to bintray seems to be in the state prior to shading sources. I have no good idea why this has changed yet, nothing has really shifted in the build since Byte Buddy 1.9.13 that would explain this deviation.

**Comment by raphw** [comment] 2019-11-28 21:32
For the record, the regression happened in Byte Buddy 1.10.3, in 1.10.2 the source jar is still correctly assembled.

**Comment by raphw** [comment] 2019-11-28 22:35
Mistery solved. The source plugin was still enabled in the *byte-buddy* module and ran in the same phase as the shade plugin. As a result, it would overwrite the shaded source jar if run after the shade plugin. The execution order seems to be machine dependent as it does not happen on one of my machines but does happen on the other.

**Comment by mirabilos** [comment] 2019-11-28 22:53
Rafael Winterhalter dixit:

>Mistery solved.

Mist lifted. Thanks for keeping us updated.

>The execution order seems to be machine dependent as it does not happen
>on one of my machines but does happen on the other.

Ouch! Shoutout for reliable tools…

**Comment by raphw** [comment] 2019-12-11 13:19
Should be fixed in the next release. Fixed on master.

**Closed by raphw** 2019-12-11 13:19 UTC
Labels: build

**Comment by mirabilos** [comment] 2020-05-12 20:44
Thanks, confirmed fixed in 1.10.10
